[[rule]]
toolName = "save_memory"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3", "grep" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "uv", "grep" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "jarvis-tts.sh" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "chmod" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "jarvis-tts.sh" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "find" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "sudo", "espeak-ng" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "python3", "sed", "timeout" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "echo", "source" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "docker", "nvidia-container-toolkit", "sudo" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "curl", "sudo", "sed" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "git", "docker" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "node" ]

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "sudo", "cd", "pnpm", "node" ]

[[rule]]
toolName = "replace"
decision = "allow"
priority = 100

[[rule]]
toolName = "run_shell_command"
decision = "allow"
priority = 100
commandPrefix = [ "cd", "mkdir", "cp", "tail", "true", "sudo", "grep" ]

[[rule]]
toolName = "write_file"
decision = "allow"
priority = 100
